receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch: # Group spans before exporting (better performance)
    send_batch_size: 512
    timeout: 5s
  memory_limiter: # Prevent OOM
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 25

exporters:
  debug:
    verbosity: detailed
  otlp/jaeger: # Export traces to Jaeger
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ debug, otlp/jaeger ]